(function () {
  // only used for poedit to find translatable strings
  let keywords = [
    _('saved.'),
    _('energy'),
    _('engineer'),
    _('spines'),
    _('meat'),
    _('shells'),
    _('supermaterials'),
    _('bullets'),
    _('charm'),
    _('bioplastic'),
    _('scrap metal'),
    _('alloy'),
    _('martion elements'),
    _('Explosives'),
    _('antimatter cell'),
    _('torch'),
    _('medicine'),
    _('hunter'),
    _('trapper'),
    _('chemist'),
    _('grenade'),
    _('bolas'),
    _('bayonet'),
    _('food_irradiator'),
    _('salvage hunter'),
    _('metal detectors'),
    _('centrifugescientist'),
    _('centrifuge'),
    _('MunitionsExpert'),
    _('ExplosivesLab'),
    _('armourer'),
    _('alloyworker'),
    _('bait'),
    _('ration packs'),
    _('scales'),
    _('SolarRover'),
    _('positronic ray'),
    _('PowerProduction'),
    _('batterys'),
    _('scales'),
    _('ration packs'),
    _('thieves'),
    _('not enough shells'),
    _('not enough energy'),
    _('not enough martion elements'),
    _('not enough scrap metal'),
    _('not enough alloy'),
    _('not enough Explosives'),
    _('baited bug trap'),
    _('not enough scales'),
    _('not enough batterys'),
    _('not enough spines'),
    _('not enough bioplastic'),
    _('not enough meat'),
    _('the solarrover points east'),
    _('the solarrover points west'),
    _('the solarrover points north'),
    _('the solarrover points south'),
    _('the solarrover points northeast'),
    _('the solarrover points northwest'),
    _('the solarrover points southeast'),
    _('the solarrover points southwest'),
  ];

  keywords = null;
}());
